# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosadamoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to=b''),
        ),
    ]
