# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosadamoapp', '0003_auto_20170207_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(default='../static/images/gallery/', upload_to='../static/images/gallery/'),
        ),
    ]
