# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosadamoapp', '0005_auto_20170207_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(default='static/images/gallery/', upload_to='static/images/gallery/'),
        ),
    ]
