# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosadamoapp', '0006_auto_20170207_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tit',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
