# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosadamoapp', '0007_image_tit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tit',
            new_name='title',
        ),
    ]
