# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosadamoapp', '0008_auto_20170207_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(verbose_name='date published')),
                ('url', models.ImageField(default='static/images/slider', upload_to='static/images/slider')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
